# Generated by Django 4.2.5 on 2023-10-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=128, verbose_name="用户名")),
                ("email", models.CharField(max_length=32, verbose_name="邮箱")),
                ("password", models.CharField(max_length=256, verbose_name="密码")),
                (
                    "signature",
                    models.CharField(
                        default="这个人很烂, 什么也没留下",
                        max_length=256,
                        null=True,
                        verbose_name="个性签名",
                    ),
                ),
                (
                    "avatar",
                    models.CharField(
                        default="http://localhost:8000/static/img/avatar/defaultAvatar.jpg",
                        max_length=256,
                        verbose_name="头像",
                    ),
                ),
                (
                    "following",
                    models.ManyToManyField(
                        blank=True, related_name="followings", to="loginManagement.user"
                    ),
                ),
            ],
        ),
    ]
